name: Auto Tag on PR Merge

on:
  push:
    branches:
      - main
      - feat/auto-publish
    paths:
      - '**/package.json'

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 使用带有权限的PAT
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check Version Change and Create Tag
        run: |
          # 找出所有修改过的package.json文件
          CHANGED_PACKAGES=$(git diff --name-only HEAD^ HEAD | grep package.json)

          # 对每个修改的package.json文件检查版本是否变更
          for PKG_FILE in $CHANGED_PACKAGES; do
            # 获取当前版本
            CURRENT_VERSION=$(cat $PKG_FILE | jq -r '.version')

            # 获取之前的版本
            PREVIOUS_VERSION=$(git show HEAD^:$PKG_FILE 2>/dev/null | jq -r '.version' 2>/dev/null)

            # 如果版本发生变化，则创建标签
            if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
              PKG_NAME=$(cat $PKG_FILE | jq -r '.name')
              TAG_NAME="v/${PKG_NAME}/${CURRENT_VERSION}"

              echo "Version changed for $PKG_NAME: $PREVIOUS_VERSION -> $CURRENT_VERSION"
              echo "Creating tag: $TAG_NAME"

              git config --local user.name "tecvan"
              git config --local user.email "tecvan.fe@gmail.com"
              git tag -a "$TAG_NAME" -m "Release $PKG_NAME@$CURRENT_VERSION"

              # 使用PAT_TOKEN推送，以便触发其他工作流
              git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
              git push origin "$TAG_NAME"
            fi
          done
